"""Coordinated disclosure pipeline (P1).

For a verified finding: novelty check against OSV, then a
HackerOne/Bugcrowd-style submission draft (markdown) saved to disclosures/.
A HUMAN reviews and sends — Aegis never submits anything.
"""

from __future__ import annotations

import re
import time
from pathlib import Path

import requests

from .db import EngagementDB

CVE_RE = re.compile(r"CVE-\d{4}-\d{4,7}", re.I)


class DisclosurePipeline:
    def __init__(self, db: EngagementDB, disclosures_dir: str | Path = "disclosures"):
        self.db = db
        self.dir = Path(disclosures_dir)
        self.dir.mkdir(parents=True, exist_ok=True)

    # ---- novelty check ---------------------------------------------------
    def novelty_check(self, finding) -> dict:
        """Query OSV for the finding's CVE / affected package. Offline-safe."""
        text = f"{finding['title']} {finding['description']}"
        cves = CVE_RE.findall(text)
        result = {"cves": cves, "osv_hits": [], "checked_at":
                  time.strftime("%Y-%m-%d %H:%M"), "error": ""}
        for cve in dict.fromkeys(cves):
            try:
                r = requests.get(f"https://api.osv.dev/v1/vulns/{cve.upper()}",
                                 timeout=15)
                if r.ok:
                    data = r.json()
                    result["osv_hits"].append({
                        "id": data.get("id", cve.upper()),
                        "summary": data.get("summary", "")[:200],
                        "published": data.get("published", ""),
                    })
            except requests.RequestException as exc:
                result["error"] = str(exc)
        return result

    # ---- draft generation --------------------------------------------------
    def draft(self, finding_id: int, *, platform: str = "hackerone") -> Path | None:
        f = self.db.get_finding(finding_id)
        if not f:
            return None
        host_row = self.db.get_target(f["target_id"])
        host = host_row["host"] if host_row else "unknown"
        novelty = self.novelty_check(f)

        L = [
            f"# {f['title']}",
            "",
            f"**Severity:** {f['severity'].upper()}"
            + (f"  ·  **CVSS:** `{f['cvss']}`" if f["cvss"] else ""),
            f"**Target:** {host}",
            f"**Provenance:** {f['provenance']}"
            + (" ✅ verified" if f["verified"] else " ⚠️ UNVERIFIED — validate before submitting"),
            f"**MITRE ATT&CK:** {f['attack_id'] or 'n/a'}",
            "",
            "## Summary",
            f["description"] or "(describe the vulnerability here)",
            "",
            "## Steps to Reproduce",
            "1. (fill in — reference the evidence below)",
            "",
            f"Evidence file: `{f['evidence'] or 'none captured'}`",
            "",
            "## Impact",
            "(describe what an attacker achieves — be concrete, tie to "
            "business impact)",
            "",
            "## Remediation",
            f["remediation"] or "(recommended fix)",
            "",
            "## Novelty Check (OSV)",
        ]
        if novelty["cves"]:
            for cve in novelty["cves"]:
                hit = next((h for h in novelty["osv_hits"]
                            if h["id"].upper() == cve.upper()), None)
                if hit:
                    L.append(f"- {cve}: known — {hit['summary']} "
                             f"(published {hit['published']})")
                else:
                    L.append(f"- {cve}: no OSV record found")
        else:
            L.append("- no CVE references in finding; manual novelty search "
                     "recommended")
        if novelty["error"]:
            L.append(f"- ⚠️ OSV check failed (offline?): {novelty['error']}")
        L += [
            "",
            "---",
            f"_Draft generated by Aegis on {novelty['checked_at']} — "
            f"review, validate, and submit manually. Platform: {platform}._",
        ]
        safe = re.sub(r"[^\w.-]+", "-", f["title"])[:60]
        out = self.dir / f"disclosure-{finding_id}-{safe}.md"
        out.write_text("\n".join(L), encoding="utf-8")
        return out
