"""Penetration-test report generator.

Renders the full engagement — scope, timeline of actions, attempts
(successes and failures), findings with evidence, and OSINT — to Markdown,
and a self-contained HTML version.
"""

from __future__ import annotations

import html
import json
import time
from pathlib import Path

from .db import EngagementDB

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


def _sev_sort(row):
    try:
        return SEVERITY_ORDER.index(row["severity"].lower())
    except ValueError:
        return len(SEVERITY_ORDER)


def _mask(value: str) -> str:
    if not value:
        return ""
    tail = value[-4:] if len(value) >= 4 else value
    return f"••••••{tail}"


class ReportGenerator:
    def __init__(self, db: EngagementDB, engagement: str,
                 reports_dir: str | Path, include_secrets: bool = False,
                 workspace: str | Path = "."):
        self.db = db
        self.engagement = engagement
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.include_secrets = include_secrets
        self.workspace = workspace

    def build_markdown(self) -> Path:
        targets = self.db.list_targets()
        all_findings = sorted(self.db.findings_for(), key=_sev_sort)
        now = time.strftime("%Y-%m-%d %H:%M")

        L: list[str] = [
            f"# Penetration Test Report — {self.engagement}",
            f"\n_Generated by Aegis Workbench on {now}_\n",
            "## Executive Summary\n",
            f"- Targets engaged: **{len(targets)}**",
            f"- Total findings: **{len(all_findings)}**",
        ]
        for sev in SEVERITY_ORDER:
            n = sum(1 for f in all_findings if f["severity"].lower() == sev)
            if n:
                L.append(f"  - {sev.capitalize()}: {n}")
        actions = self.db.conn.execute("SELECT COUNT(*) c FROM actions").fetchone()["c"]
        attempts = self.db.conn.execute("SELECT COUNT(*) c, SUM(success) s "
                                        "FROM attempts").fetchone()
        L.append(f"- Commands executed: **{actions}**")
        L.append(f"- Attack attempts: **{attempts['c']}** "
                 f"(successful: **{attempts['s'] or 0}**)\n")

        # Analyst attack narrative, if a mission produced one
        narrative = self.db.conn.execute(
            "SELECT value FROM loot WHERE kind='note' AND title='attack narrative'"
            " ORDER BY id DESC LIMIT 1").fetchone()
        if narrative and narrative["value"]:
            L.append("## Attack Narrative\n")
            L.append(narrative["value"])
            L.append("")

        L.append("## Findings (by severity)\n")
        # Only verified findings ship in the main section: tool-proven, or
        # model-asserted findings that survived the refuter pass.
        shippable = [f for f in all_findings
                     if f["status"] != "rejected"
                     and (f["verified"] or f["provenance"] == "tool-proven")]
        unverified = [f for f in all_findings
                      if f["status"] not in ("rejected",)
                      and not (f["verified"] or f["provenance"] == "tool-proven")]
        if shippable:
            for i, f in enumerate(shippable, 1):
                t = self.db.conn.execute("SELECT host FROM targets WHERE id = ?",
                                         (f["target_id"],)).fetchone()
                L += [
                    f"### {i}. [{f['severity'].upper()}] {f['title']}",
                    f"- **Target:** {t['host'] if t else '?'}",
                    f"- **Discovered:** {f['ts']}",
                    f"- **Status:** {f['status']}",
                    f"- **Provenance:** {f['provenance']}"
                    + (" ✅" if f["verified"] else ""),
                ]
                if f["cvss"]:
                    L.append(f"- **CVSS:** `{f['cvss']}`")
                if f["attack_id"]:
                    L.append(f"- **MITRE ATT&CK:** {f['attack_id']}")
                L.append(f"\n{f['description']}\n")
                if f["remediation"]:
                    L.append(f"**Remediation:** {f['remediation']}\n")
                if f["evidence"]:
                    L.append(f"- Evidence: `{f['evidence']}`")
        else:
            L.append("_No verified findings recorded._")

        if unverified:
            L.append("\n## Appendix: Unverified Candidates\n")
            L.append("_Model-asserted findings that have not passed "
                     "verification — NOT part of the confirmed results._\n")
            for f in unverified:
                note = f" — refuter: {f['refuter_note']}" if f["refuter_note"] else ""
                L.append(f"- ({f['severity']}) {f['title']} "
                         f"[{f['status']}]{note}")

        # ATT&CK coverage section
        from .attack_map import coverage, render_coverage
        L.append("\n## MITRE ATT&CK Coverage\n")
        L.append("```")
        L.append(render_coverage(coverage(self.db)))
        L.append("```\n")

        # Loot summary
        loot = self.db.loot_for()
        L.append("## Loot Summary\n")
        if loot:
            creds = [l for l in loot if l["kind"] == "credential"]
            hashes = [l for l in loot if l["kind"] == "hash"]
            files = [l for l in loot if l["kind"] in ("file", "screenshot")]
            flags = [l for l in loot if l["kind"] == "flag"]
            L.append(f"- Credentials captured: **{len(creds)}**")
            L.append(f"- Hashes captured: **{len(hashes)}**")
            L.append(f"- Files/screenshots: **{len(files)}**")
            L.append(f"- Flags captured: **{len(flags)}**\n")
            for l in flags:
                host = self.db.get_target(l["target_id"])
                L.append(f"- 🚩 `{host['host'] if host else '?'}` "
                         f"{l['title']}: `{l['value']}`")
            for l in creds:
                host = self.db.get_target(l["target_id"])
                value = l["value"] if self.include_secrets else _mask(l["value"])
                L.append(f"- 🔑 `{host['host'] if host else '?'}` "
                         f"{l['title']}: `{value}`")
        else:
            L.append("_No loot captured._")

        # Engagement knowledge base — what this engagement taught the tool
        from .playbook import list_custom_rules
        custom = list_custom_rules(self.workspace)
        live_rules = ([("version", r[0], r[1])
                       for r in custom.get("version_hints", [])]
                      + [("service", r[0], r[1])
                         for r in custom.get("service_hints", [])]
                      + [("port", k, v)
                         for k, v in custom.get("port_hints", {}).items()])
        drafts = custom.get("drafts", [])
        if live_rules or drafts:
            L.append("\n## Engagement Knowledge Base\n")
            L.append("_Techniques learned or operator-added during this "
                     "engagement — they make the next engagement against this "
                     "stack faster._\n")
            for group, pattern, hint in live_rules:
                L.append(f"- ✅ **live** ({group}) `{pattern}` — {hint}")
            for d in drafts:
                L.append(f"- ⏳ **pending review** ({d['group']}) "
                         f"`{d['pattern']}` — {d['hint']}")

        L.append("\n## Targets Detail\n")
        for t in targets:
            L.append(f"### {t['host']} — {t['status']}")
            if t["description"]:
                L.append(f"_{t['description']}_\n")
            # infrastructure profile (deterministically extracted intel)
            intel = self.db.intel_for(t["id"])
            if intel:
                services = [i for i in intel if i["kind"] == "service"]
                web = [i for i in intel if i["kind"] == "web"]
                oses = [i for i in intel if i["kind"] == "os"]
                tech = [i for i in intel if i["kind"] == "tech"]
                if services:
                    L.append("**Infrastructure:**\n")
                    L.append("| Port | Service / version |")
                    L.append("|---|---|")
                    for s in services:
                        L.append(f"| `{s['key']}` | {s['value']} |")
                    L.append("")
                if web:
                    L.append("**Web stack:** " + " · ".join(
                        f"{i['key']}: `{i['value']}`" for i in web) + "\n")
                if oses:
                    L.append("**OS:** " + " · ".join(
                        f"`{i['value']}`" for i in oses) + "\n")
                if tech:
                    L.append("**Technologies:** " + " · ".join(
                        f"`{i['value']}`" for i in tech) + "\n")
            osint = self.db.osint_for(t["id"])
            if osint:
                L.append("**OSINT:**\n")
                for o in osint[:15]:
                    data = o["data"][:160].replace("\n", " ")
                    L.append(f"- `{o['source']}/{o['kind']}`: {data}")
            attempts_t = self.db.attempts_for(t["id"])
            if attempts_t:
                L.append("\n**Attempts:**\n")
                for a in attempts_t:
                    mark = "✅" if a["success"] else "❌"
                    tag = f" `{a['attack_id']}`" if a["attack_id"] else ""
                    L.append(f"- {mark} **{a['technique']}** ({a['vector']}){tag} — "
                             f"{a['result'][:160]}")
            loot_t = self.db.loot_for(t["id"])
            if loot_t:
                L.append("\n**Loot:**\n")
                for l in loot_t:
                    if l["kind"] in ("credential", "hash") and not self.include_secrets:
                        ref = _mask(l["value"])
                    else:
                        ref = l["file_path"] or l["value"][:100]
                    L.append(f"- ({l['kind']}) {l['title']}: `{ref}`")
            actions_t = self.db.conn.execute(
                "SELECT ts, command, exit_code, status FROM actions"
                " WHERE target_id = ? ORDER BY id", (t["id"],)).fetchall()
            if actions_t:
                L.append("\n**Action log:**\n")
                for a in actions_t:
                    L.append(f"- `{a['ts']}` `{a['command']}` "
                             f"(exit {a['exit_code']}, {a['status']})")
            L.append("")

        L.append("## Appendix: Audit Trail\n")
        L.append("All activity is recorded in the tamper-evident audit chain "
                 "in `logs/audit-*.jsonl` (hash-linked; verify with "
                 "`python main.py /verify-audit`).\n")

        path = self.reports_dir / f"report-{self.engagement}.md"
        path.write_text("\n".join(L), encoding="utf-8")
        return path

    def build_html(self, md_path: Path) -> Path:
        md = md_path.read_text(encoding="utf-8")
        body_lines = []
        table_buf: list[str] = []

        def flush_table():
            if not table_buf:
                return
            rows = [r for r in table_buf
                    if not set(r.strip()) <= set("|-: ")]
            if rows:
                out = ["<table>"]
                for ri, r in enumerate(rows):
                    cells = [c.strip() for c in r.strip().strip("|").split("|")]
                    tag = "th" if ri == 0 else "td"
                    out.append("<tr>" + "".join(
                        f"<{tag}>{html.escape(c)}</{tag}>"
                        for c in cells) + "</tr>")
                out.append("</table>")
                body_lines.append("".join(out))
            table_buf.clear()

        for ln in md.splitlines():
            if ln.startswith("|"):
                table_buf.append(ln)
                continue
            flush_table()
            esc = html.escape(ln)
            if ln.startswith("### "):
                body_lines.append(f"<h3>{html.escape(ln[4:])}</h3>")
            elif ln.startswith("## "):
                body_lines.append(f"<h2>{html.escape(ln[3:])}</h2>")
            elif ln.startswith("# "):
                body_lines.append(f"<h1>{html.escape(ln[2:])}</h1>")
            elif ln.startswith("- "):
                body_lines.append(f"<li>{esc[2:]}</li>")
            elif ln.strip():
                body_lines.append(f"<p>{esc}</p>")
        flush_table()
        page = f"""<!doctype html><html><head><meta charset="utf-8">
<title>Report — {html.escape(self.engagement)}</title>
<style>body{{font-family:system-ui,sans-serif;max-width:960px;margin:2rem auto;
padding:0 1rem;line-height:1.55}} code{{background:#f0f0f0;padding:0 .3em;
border-radius:4px}} h1,h2,h3{{color:#12355b}} li{{margin:.15rem 0}}
table{{border-collapse:collapse;margin:.5rem 0}} td,th{{border:1px solid #cbd5e1;
padding:.3rem .7rem;text-align:left;font-size:.9rem}} th{{background:#eef2f7}}</style>
</head><body>{''.join(body_lines)}</body></html>"""
        out = md_path.with_suffix(".html")
        out.write_text(page, encoding="utf-8")
        return out
