"""Penetration-test report generator.

Renders the full engagement — scope, timeline of actions, attempts
(successes and failures), findings with evidence, and OSINT — to Markdown,
and a self-contained HTML version.
"""

from __future__ import annotations

import html
import json
import time
from pathlib import Path

from .db import EngagementDB

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


def _sev_sort(row):
    try:
        return SEVERITY_ORDER.index(row["severity"].lower())
    except ValueError:
        return len(SEVERITY_ORDER)


def _mask(value: str) -> str:
    if not value:
        return ""
    tail = value[-4:] if len(value) >= 4 else value
    return f"••••••{tail}"


class ReportGenerator:
    def __init__(self, db: EngagementDB, engagement: str,
                 reports_dir: str | Path, include_secrets: bool = False):
        self.db = db
        self.engagement = engagement
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.include_secrets = include_secrets

    def build_markdown(self) -> Path:
        targets = self.db.list_targets()
        all_findings = sorted(self.db.findings_for(), key=_sev_sort)
        now = time.strftime("%Y-%m-%d %H:%M")

        L: list[str] = [
            f"# Penetration Test Report — {self.engagement}",
            f"\n_Generated by Aegis Workbench on {now}_\n",
            "## Executive Summary\n",
            f"- Targets engaged: **{len(targets)}**",
            f"- Total findings: **{len(all_findings)}**",
        ]
        for sev in SEVERITY_ORDER:
            n = sum(1 for f in all_findings if f["severity"].lower() == sev)
            if n:
                L.append(f"  - {sev.capitalize()}: {n}")
        actions = self.db.conn.execute("SELECT COUNT(*) c FROM actions").fetchone()["c"]
        attempts = self.db.conn.execute("SELECT COUNT(*) c, SUM(success) s "
                                        "FROM attempts").fetchone()
        L.append(f"- Commands executed: **{actions}**")
        L.append(f"- Attack attempts: **{attempts['c']}** "
                 f"(successful: **{attempts['s'] or 0}**)\n")

        L.append("## Findings (by severity)\n")
        if all_findings:
            for i, f in enumerate(all_findings, 1):
                t = self.db.conn.execute("SELECT host FROM targets WHERE id = ?",
                                         (f["target_id"],)).fetchone()
                L += [
                    f"### {i}. [{f['severity'].upper()}] {f['title']}",
                    f"- **Target:** {t['host'] if t else '?'}",
                    f"- **Discovered:** {f['ts']}",
                    f"- **Status:** {f['status']}",
                ]
                if f["cvss"]:
                    L.append(f"- **CVSS:** `{f['cvss']}`")
                if f["attack_id"]:
                    L.append(f"- **MITRE ATT&CK:** {f['attack_id']}")
                L.append(f"\n{f['description']}\n")
                if f["remediation"]:
                    L.append(f"**Remediation:** {f['remediation']}\n")
                if f["evidence"]:
                    L.append(f"- Evidence: `{f['evidence']}`")
        else:
            L.append("_No findings recorded._")

        # ATT&CK coverage section
        from .attack_map import coverage, render_coverage
        L.append("\n## MITRE ATT&CK Coverage\n")
        L.append("```")
        L.append(render_coverage(coverage(self.db)))
        L.append("```\n")

        # Loot summary
        loot = self.db.loot_for()
        L.append("## Loot Summary\n")
        if loot:
            creds = [l for l in loot if l["kind"] == "credential"]
            hashes = [l for l in loot if l["kind"] == "hash"]
            files = [l for l in loot if l["kind"] in ("file", "screenshot")]
            L.append(f"- Credentials captured: **{len(creds)}**")
            L.append(f"- Hashes captured: **{len(hashes)}**")
            L.append(f"- Files/screenshots: **{len(files)}**\n")
            for l in creds:
                host = self.db.get_target(l["target_id"])
                value = l["value"] if self.include_secrets else _mask(l["value"])
                L.append(f"- 🔑 `{host['host'] if host else '?'}` "
                         f"{l['title']}: `{value}`")
        else:
            L.append("_No loot captured._")

        L.append("\n## Targets Detail\n")
        for t in targets:
            L.append(f"### {t['host']} — {t['status']}")
            if t["description"]:
                L.append(f"_{t['description']}_\n")
            osint = self.db.osint_for(t["id"])
            if osint:
                L.append("**OSINT:**\n")
                for o in osint[:15]:
                    data = o["data"][:160].replace("\n", " ")
                    L.append(f"- `{o['source']}/{o['kind']}`: {data}")
            attempts_t = self.db.attempts_for(t["id"])
            if attempts_t:
                L.append("\n**Attempts:**\n")
                for a in attempts_t:
                    mark = "✅" if a["success"] else "❌"
                    tag = f" `{a['attack_id']}`" if a["attack_id"] else ""
                    L.append(f"- {mark} **{a['technique']}** ({a['vector']}){tag} — "
                             f"{a['result'][:160]}")
            loot_t = self.db.loot_for(t["id"])
            if loot_t:
                L.append("\n**Loot:**\n")
                for l in loot_t:
                    if l["kind"] in ("credential", "hash") and not self.include_secrets:
                        ref = _mask(l["value"])
                    else:
                        ref = l["file_path"] or l["value"][:100]
                    L.append(f"- ({l['kind']}) {l['title']}: `{ref}`")
            actions_t = self.db.conn.execute(
                "SELECT ts, command, exit_code, status FROM actions"
                " WHERE target_id = ? ORDER BY id", (t["id"],)).fetchall()
            if actions_t:
                L.append("\n**Action log:**\n")
                for a in actions_t:
                    L.append(f"- `{a['ts']}` `{a['command']}` "
                             f"(exit {a['exit_code']}, {a['status']})")
            L.append("")

        L.append("## Appendix: Audit Trail\n")
        L.append("All activity is recorded in the tamper-evident audit chain "
                 "in `logs/audit-*.jsonl` (hash-linked; verify with "
                 "`python main.py /verify-audit`).\n")

        path = self.reports_dir / f"report-{self.engagement}.md"
        path.write_text("\n".join(L), encoding="utf-8")
        return path

    def build_html(self, md_path: Path) -> Path:
        md = md_path.read_text(encoding="utf-8")
        body_lines = []
        for ln in md.splitlines():
            esc = html.escape(ln)
            if ln.startswith("### "):
                body_lines.append(f"<h3>{html.escape(ln[4:])}</h3>")
            elif ln.startswith("## "):
                body_lines.append(f"<h2>{html.escape(ln[3:])}</h2>")
            elif ln.startswith("# "):
                body_lines.append(f"<h1>{html.escape(ln[2:])}</h1>")
            elif ln.startswith("- "):
                body_lines.append(f"<li>{esc[2:]}</li>")
            elif ln.strip():
                body_lines.append(f"<p>{esc}</p>")
        page = f"""<!doctype html><html><head><meta charset="utf-8">
<title>Report — {html.escape(self.engagement)}</title>
<style>body{{font-family:system-ui,sans-serif;max-width:960px;margin:2rem auto;
padding:0 1rem;line-height:1.55}} code{{background:#f0f0f0;padding:0 .3em;
border-radius:4px}} h1,h2,h3{{color:#12355b}} li{{margin:.15rem 0}}</style>
</head><body>{''.join(body_lines)}</body></html>"""
        out = md_path.with_suffix(".html")
        out.write_text(page, encoding="utf-8")
        return out
